### ISSUE TITLE
这里是不是有问题呀 还有楼主可以给一个效果图吗？

### ISSUE THREAD

**Issue by luoxin2** [ShowLo/FatigueDetection#1]
![Screenshot_2019-04-11 ShowLo FatigueDetection](https://user-images.githubusercontent.com/33897012/55940503-d7ea6280-5c72-11e9-8969-a6c87e145d03.png)

**Comment by ShowLo** [comment]
这里的意思是假设人脸肤色有个从minValue到maxValue的范围，超过这个范围的都置为0。图片可能涉及隐私问题不便放出来，你可以自己找图片跑一下

**Comment by luoxin2** [comment]
嗯嗯 还想问下楼主calling检测 是否受光线影响很大 我看代码里阈值都不一样 是否是光线原因？还有就是为什么findMaxConnectedComponent找到的和肤色联通域在我测试的图片上效果很差？这个精确度高吗？

**Comment by ShowLo** [comment]
对，连通区域与肤色范围以及阈值的选择还是有比较大的关系的，想要精确度高的话建议可以选择机器学习的方法去检测手部

**Comment by luoxin2** [comment]
好的 非常感谢
